import type { Metadata } from "next";
import React from "react";
import BackBtn from "./BackBtn";

export const metadata: Metadata = {
  title: "Tasks",
  description: "Generated by create next app",
};

export default function AddTaskLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="flex flex-col items-end">
      <BackBtn />
      <div className="mt-8 w-full">{children}</div>
    </div>
  );
}
