import Header from "@/components/header";
import "./globals.css";
import { Inter } from "next/font/google";
import AddBtn from "./AddBtn";

const inter = Inter({ subsets: ["latin"] });
// export const revalidate = 0;
export const metadata = {
  title: "Todo App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <div className="mt-5 px-5">{children}</div>
        <AddBtn />
      </body>
    </html>
  );
}
