import type { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Add new task",
  description: "Generated by create next app",
};

export default function AddTaskLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <div className="mt-20 mx-96">{children}</div>;
}
